### PR TITLE
portable.h: fix build with gcc older than 4.8

### PR DESCRIPTION
**Pull request by baruchsiach**
__builtin_bswap16 is available in all gcc architectures only since
version 4.8. Older gcc versions fail to build:

imx_sdp.o: In function `perform_dcd':
.../imx_sdp.c:1138: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `write_dcd_table_ivt':
.../imx_sdp.c:457: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `write_dcd':
.../imx_sdp.c:410: undefined reference to `__builtin_bswap16'
imx_sdp.o: In function `init_header':
.../imx_sdp.c:1075: undefined reference to `__builtin_bswap16'

Use a local implementation instead.

Signed-off-by: Baruch Siach <baruch@tkos.co.il>

### CODE REVIEW

**Comment by baruchsiach** [comment]
Updated the patch to make the byte swap macro more robust.

**Comment by gibsson** [comment]
Thanks for the patch!
